### ISSUE TITLE
下载不动 

### ISSUE THREAD

**Issue by XinKerrr** [aiguoli/qcourse_scripts#11]
![QQ截图20210922203618](https://user-images.githubusercontent.com/60815889/134344773-f42b28a0-5992-4c9a-ad9d-d72da09fb760.png)

**Comment by aiguoli** [comment]
你看眼文件夹里，其实是可以下载的，不过异步下载后这个进度条实现的有点拉跨

**Comment by aiguoli** [comment]
进度条问题解决了
