### ISSUE TITLE
视频能正常下载，解码出现错误

### ISSUE THREAD

**Issue by gooapple** [aiguoli/qcourse_scripts#19]
![image](https://user-images.githubusercontent.com/54422589/147652194-36aa13ac-1574-44b3-a745-4fcef8c88464.png)

大佬，你的代码这个地方，课程id和termid是写死的，我给你修改了。下载没有问题，但是解码那里出问题了

![image](https://user-images.githubusercontent.com/54422589/147653454-cee143b8-5cda-4f09-942a-ebb4b7c0fe40.png)

**Comment by aiguoli** [comment]
token问题已经修复了，解码那块出问题估计是视频没下载完整
