### ISSUE TITLE
2022.4.18 13:20 tx课堂接口 报错

### ISSUE THREAD

**Issue by POIB** [aiguoli/qcourse_scripts#34]
https://ke.qq.com/cgi-bin/course/basic_info?cid=
上面这个接口要带防盗链，不然查询不到参数
错误的返回：{"msg":"refer错误","type":1,"retcode":100101}

建议解决办法：
在utils.py文件里，的get_course_from_api函数中，添加headers参数
如：    
'''
headers = {
        'referer': 'https://ke.qq.com/user/index/index.html',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                      'Chrome/80.0.3987.132 Safari/537.36 '
    }
'''
即可

完整函数：
''' python
def get_course_from_api(cid=None):
    headers = {
        'referer': 'https://ke.qq.com/user/index/index.html',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                      'Chrome/80.0.3987.132 Safari/537.36 '
    }
    # 获取课程信息
    if cid is None:
        print('请输入cid！')
    url = 'https://ke.qq.com/cgi-bin/course/basic_info?cid=' + str(cid)
    response = requests.get(url=url, headers=headers).json()
    name = response.get('result').get('course_detail').get('name').replace('/', '／').replace('\\', '＼')
    with open(name + '.json', 'w') as f:
        f.write(json.dumps(response))
    return name
'''

**Comment by aiguoli** [comment]
目前的代码里有Refer
```python
def get_course_from_api(cid):
    # 获取课程信息
    # url = 'https://ke.qq.com/cgi-bin/course/basic_info?cid=' + str(cid)
    url = API.BasicInfoUri.format(cid=cid)
    response = requests.get(url, headers=DEFAULT_HEADERS).json()
    name = (
        response.get('result')
        .get('course_detail')
        .get('name')
        .replace('/', '／')
        .replace('\\', '＼')
    )
    with open(name + '.json', 'w') as f:
        json.dump(response, f, ensure_ascii=False, indent=4)
    return name
```

**Comment by POIB** [comment]
无法获取到uin，请输入你的QQ：
输入自己的请求后输出：
[21/Apr/2022 16:10:06] INFO - p_lskey: ***, ptui_loginuin: ***, skey: @***, p_skey: ###-###
（***是数字 小写 字符串，###包含大小写 数字 字符串）
之后又输出“无法获取到uin，请输入你的QQ：”

**Comment by aiguoli** [comment]
问题解决了，更新脚本试试
