### ISSUE TITLE
pip install -Ur requirements.txt报错，换源未解决

### ISSUE THREAD

**Issue by Caryio** [aiguoli/qcourse_scripts#39]
大佬好！请教一下，我在pip install -Ur requirements.txt这一步报错，按照一个已关闭的issue（https://github.com/aiguoli/qcourse_scripts/issues/21） 里的换源的方法未解决

设备版本：
win10 21H2，python3.10.5
没放在C盘，放在文件夹：E:\qcourse_scripts-main

复现过程：
我先在cmd里执行了cd E:\qcourse_scripts-main，然后python -m venv qcourse-venv、qcourse-venv\scripts\activate
此进入到了一个新的命令行界面，然后执行pip install -Ur E:\qcourse_scripts-main\requirements.txt，出现和一个已关闭的issue（https://github.com/aiguoli/qcourse_scripts/issues/21） 里相同错误，于是执行了永久换源pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple ，然后再pip install -Ur E:\qcourse_scripts-main\requirements.txt，没有任何变化，仍然出现相同错误。
请问如何解决呢？

报错如下：

Using legacy 'setup.py install' for greenlet, since package 'wheel' is not installed.
Using legacy 'setup.py install' for Pillow, since package 'wheel' is not installed.
Using legacy 'setup.py install' for websockets, since package 'wheel' is not installed.
Building wheels for collected packages: multidict, yarl, aiohttp
  Building wheel for multidict (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for multidict (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\multidict
      copying multidict\_abc.py -> build\lib.win-amd64-cpython-310\multidict
      copying multidict\_compat.py -> build\lib.win-amd64-cpython-310\multidict
      copying multidict\_multidict_base.py -> build\lib.win-amd64-cpython-310\multidict
      copying multidict\_multidict_py.py -> build\lib.win-amd64-cpython-310\multidict
      copying multidict\__init__.py -> build\lib.win-amd64-cpython-310\multidict
      running egg_info
      writing multidict.egg-info\PKG-INFO
      writing dependency_links to multidict.egg-info\dependency_links.txt
      writing top-level names to multidict.egg-info\top_level.txt
      reading manifest file 'multidict.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files found matching 'multidict\_multidict.html'
      warning: no previously-included files found matching 'multidict\*.so'
      warning: no previously-included files found matching 'multidict\*.pyd'
      warning: no previously-included files found matching 'multidict\*.pyd'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE'
      writing manifest file 'multidict.egg-info\SOURCES.txt'
      C:\Users\Yunjiao\AppData\Local\Temp\pip-build-env-ktti29ps\overlay\Lib\site-packages\setuptools\command\build_py.py:153: SetuptoolsDeprecationWarning:     Installing 'multidict._multilib' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'multidict._multilib' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'multidict._multilib' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'multidict._multilib' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      copying multidict\__init__.pyi -> build\lib.win-amd64-cpython-310\multidict
      copying multidict\_multidict.c -> build\lib.win-amd64-cpython-310\multidict
      copying multidict\py.typed -> build\lib.win-amd64-cpython-310\multidict
      creating build\lib.win-amd64-cpython-310\multidict\_multilib
      copying multidict\_multilib\defs.h -> build\lib.win-amd64-cpython-310\multidict\_multilib
      copying multidict\_multilib\dict.h -> build\lib.win-amd64-cpython-310\multidict\_multilib
      copying multidict\_multilib\istr.h -> build\lib.win-amd64-cpython-310\multidict\_multilib
      copying multidict\_multilib\iter.h -> build\lib.win-amd64-cpython-310\multidict\_multilib
      copying multidict\_multilib\pair_list.h -> build\lib.win-amd64-cpython-310\multidict\_multilib
      copying multidict\_multilib\views.h -> build\lib.win-amd64-cpython-310\multidict\_multilib
      running build_ext
      building 'multidict._multidict' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for multidict
  Building wheel for yarl (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for yarl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      C:\Users\Yunjiao\AppData\Local\Temp\pip-build-env-h9nyg2us\overlay\Lib\site-packages\setuptools\config\setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      **********************
      * Accellerated build *
      **********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\yarl
      copying yarl\_quoting.py -> build\lib.win-amd64-cpython-310\yarl
      copying yarl\_quoting_py.py -> build\lib.win-amd64-cpython-310\yarl
      copying yarl\_url.py -> build\lib.win-amd64-cpython-310\yarl
      copying yarl\__init__.py -> build\lib.win-amd64-cpython-310\yarl
      running egg_info
      writing yarl.egg-info\PKG-INFO
      writing dependency_links to yarl.egg-info\dependency_links.txt
      writing requirements to yarl.egg-info\requires.txt
      writing top-level names to yarl.egg-info\top_level.txt
      reading manifest file 'yarl.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.cache' found anywhere in distribution
      warning: no previously-included files found matching 'yarl\*.html'
      warning: no previously-included files found matching 'yarl\*.so'
      warning: no previously-included files found matching 'yarl\*.pyd'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE'
      writing manifest file 'yarl.egg-info\SOURCES.txt'
      copying yarl\__init__.pyi -> build\lib.win-amd64-cpython-310\yarl
      copying yarl\_quoting_c.c -> build\lib.win-amd64-cpython-310\yarl
      copying yarl\_quoting_c.pyi -> build\lib.win-amd64-cpython-310\yarl
      copying yarl\_quoting_c.pyx -> build\lib.win-amd64-cpython-310\yarl
      copying yarl\py.typed -> build\lib.win-amd64-cpython-310\yarl
      running build_ext
      building 'yarl._quoting_c' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for yarl
  Building wheel for aiohttp (pyproject.toml) ... done
  Created wheel for aiohttp: filename=aiohttp-3.7.4.post0-py3-none-any.whl size=451929 sha256=0288973d36fcbc49aa0bf515aea84a11ec600ddbb79229cd38d6dab991a97228
  Stored in directory: c:\users\yunjiao\appdata\local\pip\cache\wheels\a3\57\55\959e243754be9b2979a138ba11d22a4a5538b1b1620d0510cd
Successfully built aiohttp
Failed to build multidict yarl
ERROR: Could not build wheels for multidict, yarl, which is required to install pyproject.toml-based projects
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the 'C:\Users\Yunjiao\qcourse-venv\Scripts\python.exe -m pip install --upgrade pip' command.

**Comment by aiguoli** [comment]
输入`pip install wheel`试试，如果还是不行，输入`pip list`我看看
