### ISSUE TITLE
不行啊，完整课程下载失败！

### ISSUE THREAD

**Issue by lvgitt** [aiguoli/qcourse_scripts#4]
cid:231516

**Comment by lvgitt** [comment]
一些付费课程下不了，建议增加登录功能，下载自己已购买的课程

**Comment by aiguoli** [comment]
有登录功能，如果失效了就把目录下的`cookies.json`删掉。
下载失败有没有报错信息

**Comment by lvgitt** [comment]
抓取的目录不对
![image](https://user-images.githubusercontent.com/44693144/119096356-12c04680-ba46-11eb-85d0-34de0b86b76c.png)
![image](https://user-images.githubusercontent.com/44693144/119096450-31264200-ba46-11eb-9083-c69eef8de86b.png)

**Comment by aiguoli** [comment]
现在应该没问题了，我没有这个课程，你再试一下

**Comment by bg4vrg** [comment]
多谢！目前测试前2种下载没问题，第三种下载全部的会报错，不过影响不大，我慢慢下载。

**Comment by aiguoli** [comment]
疏忽了，已经解决

**Comment by lvgitt** [comment]
![image](https://user-images.githubusercontent.com/44693144/120182718-55053700-c241-11eb-8a58-596c57de1c29.png)
这是啥情况
