### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by hackpwnpwn** [aiguoli/qcourse_scripts#42]
qcourse-venv) F:\tx\qcourse_scripts-main>playwright install msedge
Failed to install browsers
Error:
╔═════════════════════════════════════════════════════════════════╗
║ ATTENTION: "msedge" is already installed on the system!         ║
║                                                                 ║
║ "msedge" installation is not hermetic; installing newer version ║
║ requires *removal* of a current installation first.             ║
║                                                                 ║
║ To *uninstall* current version and re-install latest "msedge":  ║
║                                                                 ║
║ - Close all running instances of "msedge", if any               ║
║ - Use "--force" to install browser:                             ║
║                                                                 ║
║     playwright install --force msedge                           ║
║                                                                 ║
║ <3 Playwright Team                                              ║
╚═════════════════════════════════════════════════════════════════╝

**Comment by aiguoli** [comment]
更新一下，新版本去除playwright依赖了
