### ISSUE TITLE
求教大佬

### ISSUE THREAD

**Issue by BrightMoonInner** [aiguoli/qcourse_scripts#8]
前面的结果步骤ok，但是到了这一步：playwright install msedge
出现了如下的错误提示：

无法加载文件 D:\Users\Desktop\qcourse_scripts-main\qcourse-venv\Lib\site-packag
es\playwright\driver\package\bin\reinstall_msedge_stable_win.ps1，因为在此系统
中禁止执行脚本。有关详细信息，请参阅 "get-help about_signing"。
所在位置 行:1 字符: 131
+ d:\Users\Desktop\qcourse_scripts-main\qcourse-venv\Lib\site-packages\playwrig
ht\driver\package\bin\reinstall_msedge_stable_win.ps1 <<<<  https://msedge.sf.d
l.delivery.mp.microsoft.com/filestreamingservice/files/2521c007-c376-4e08-8570-
6d8526416a27/MicrosoftEdgeEnterpriseX64.msi
    + CategoryInfo          : NotSpecified: (:) [], PSSecurityException
    + FullyQualifiedErrorId : RuntimeException

Failed to install browsers
Error: Failed to install msedge

如果不理会它，继续进行最后一步：python qcourse.py，
得到这样的日志：

0. 下载单个视频
1. 下载课程指定章节
2. 下载课程全部视频

输入需要的功能：0
Traceback (most recent call last):
  File "d:\Users\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pla
ywright\_impl\_browser_type.py", line 86, in launch
    return from_channel(await self._channel.send("launch", params))
  File "d:\Users\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pla
ywright\_impl\_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "d:\Users\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pla
ywright\_impl\_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Chromium distribution 'msedge' is not found a
t C:\Users\Administrator\AppData\Local\Microsoft\Edge\Application\msedge.exe
Run "npx playwright install msedge"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qcourse.py", line 137, in <module>
    main()
  File "qcourse.py", line 92, in main
    qq_course = QCourse()
  File "qcourse.py", line 22, in __init__
    self.browser = self.p.chromium.launch(channel='msedge', headless=False)
  File "d:\Users\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pla
ywright\sync_api\_generated.py", line 9703, in launch
    self._sync(
  File "d:\Users\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pla
ywright\_impl\_sync_base.py", line 111, in _sync
    return task.result()
  File "d:\Users\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pla
ywright\_impl\_browser_type.py", line 89, in launch
    raise not_installed_error(f'"{self.name}" browser was not found.')
playwright._impl._api_types.Error:
================================================================================

"chromium" browser was not found.
Please complete Playwright installation via running

    "python -m playwright install"

================================================================================

不知道出了什么问题……麻烦大佬给看看，谢谢♪(･ω･)ﾉ

**Comment by FupengWang** [comment]
运行`playwright install msedge`出现错误, 请用管理员权限打开powershell, 然后输入`set-executionpolicy remotesigned`, 再键入`y`, 安装完edge后再进行后面的操作.

**Comment by hiifong** [comment]
![image](https://user-images.githubusercontent.com/89133723/163990083-e99e2ecf-da79-4396-a4cb-1ebdb55492b6.png)
我设置了还是不行
