### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by FupengWang** [aiguoli/qcourse_scripts#9]
尝试下载整套课程时
![1](https://user-images.githubusercontent.com/61930606/132099670-5cd03bd0-6f2a-4c16-95b1-4221adf6d2df.png)
`utils.py`49 - 55
```
def get_chapters_from_file(filename, term_index):
    # 从json文件内获取章节信息
    with open(filename, 'r') as f:
        course_info = json.loads(f.read())
    chapters = course_info.get('result').get('course_detail').get('terms')[term_index].get('chapter_info')[0]\
        .get('sub_info')
    return chapters
```
手动修改`term_index`为目标学期时, 出现下面的错误
![2](https://user-images.githubusercontent.com/61930606/132099717-2774e929-c809-4702-a088-85ee0e969110.png)

**Comment by aiguoli** [comment]
更新下脚本试试看

**Comment by FupengWang** [comment]
出现了新的报错信息
![2](https://user-images.githubusercontent.com/61930606/132324493-c13a62da-34a7-454f-ba40-5b8ad44d8769.png)
